#+ summary: Find things introduced in signed nanopublications that are not retracted or superseded
#+ endpoint: https://virtuoso.nps.petapico.org/sparql
#+ method: GET
#+ tags:
#+   - json
#+ pagination: 1000
#+ endpoint_in_url: False

prefix npx: <http://purl.org/nanopub/x/>

select * where { ?service rdf:type npx:NanopubService . ?service rdfs:label ?label . }
